version: "3.8"

services:
  phoenix:
    build: "."
    env_file:
      - .env
    environment:
      MIX_ENV: dev
    restart: always
    volumes:
      - ./:/app
    ports:
      - "4020:4020"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - /pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  pgdata: